version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true
    command: gatsby develop -H 0.0.0.0
